services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-models:/root/.ollama
    restart: always

  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    restart: always
    volumes:
      - ./api:/usr/src/app
